package main

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/http/httputil"
	"net/url"
	"os"
	"os/exec"
	"strings"
	"text/template"
	"time"
)

// CreateProxyHandler creates a reverse proxy handler with:
// - path prefix stripping (basePath removed before forwarding)
// - response rewriting (asset paths like /_next/ rewritten to /basePath/_next/)
func CreateProxyHandler(target string, basePath string) http.Handler {
	targetURL, err := url.Parse(target)
	if err != nil {
		log.Fatalf("Bad target URL %q: %v", target, err)
	}

	proxy := httputil.NewSingleHostReverseProxy(targetURL)

	// Director: strip basePath before forwarding to upstream
	proxy.Director = func(req *http.Request) {
		req.URL.Scheme = targetURL.Scheme
		req.URL.Host = targetURL.Host

		// Strip basePath prefix
		stripped := strings.TrimPrefix(req.URL.Path, basePath)
		if stripped == "" || stripped[0] != '/' {
			stripped = "/" + stripped
		}
		req.URL.Path = stripped

		// Tell upstream about original prefix (useful for some frameworks)
		req.Header.Set("X-Forwarded-Prefix", basePath)
		req.Header.Set("X-Real-IP", req.RemoteAddr)

		// Accept-Encoding: keep gzip but we handle decompression in ModifyResponse
		if req.Header.Get("Accept-Encoding") != "" {
			req.Header.Set("Accept-Encoding", "gzip")
		}
	}

	// ModifyResponse: rewrite asset paths in HTML/JS/CSS responses
	proxy.ModifyResponse = func(resp *http.Response) error {
		ct := resp.Header.Get("Content-Type")
		isRewritable := strings.Contains(ct, "text/html") ||
			strings.Contains(ct, "javascript") ||
			strings.Contains(ct, "text/css")

		if !isRewritable {
			return nil
		}

		// Read body (handle gzip)
		var bodyBytes []byte
		isGzip := resp.Header.Get("Content-Encoding") == "gzip"

		if isGzip {
			gr, err := gzip.NewReader(resp.Body)
			if err != nil {
				return nil // can't decode, skip rewriting
			}
			defer gr.Close()
			bodyBytes, err = io.ReadAll(gr)
			if err != nil {
				return nil
			}
		} else {
			var err error
			bodyBytes, err = io.ReadAll(resp.Body)
			if err != nil {
				return nil
			}
		}
		resp.Body.Close()

		// Rewrite absolute paths that Next.js / Vite / CRA generate:
		// /_next/   → /basePath/_next/
		// /__nextjs → /basePath/__nextjs
		// /_next/image → /basePath/_next/image
		// /favicon  → /basePath/favicon  (only in HTML)
		body := string(bodyBytes)

		// Patterns to rewrite — order matters (more specific first)
		replacements := []struct{ from, to string }{
			{`"/_next/`, `"` + basePath + `/_next/`},
			{`'/_next/`, `'` + basePath + `/_next/`},
			{"=/_next/", "=" + basePath + "/_next/"},
			{`"/__nextjs`, `"` + basePath + `/__nextjs`},
			{`'/__nextjs`, `'` + basePath + `/__nextjs`},
			// next/image src rewriting
			{`url=/_`, `url=` + basePath + `/_`},
			{`/_next/image`, basePath + `/_next/image`},
		}

		// Only in HTML: rewrite root-relative links (/favicon, /images, etc.)
		if strings.Contains(ct, "text/html") {
			replacements = append(replacements,
				struct{ from, to string }{`href="/`, `href="` + basePath + `/`},
				struct{ from, to string }{`action="/`, `action="` + basePath + `/`},
			)
		}

		for _, r := range replacements {
			body = strings.ReplaceAll(body, r.from, r.to)
		}

		// Re-encode as plain (remove gzip since we decompressed)
		newBody := []byte(body)
		resp.Body = io.NopCloser(bytes.NewReader(newBody))
		resp.ContentLength = int64(len(newBody))
		resp.Header.Del("Content-Encoding") // no longer gzip
		resp.Header.Set("Content-Length", fmt.Sprintf("%d", len(newBody)))

		return nil
	}

	proxy.ErrorHandler = func(w http.ResponseWriter, r *http.Request, err error) {
		log.Printf("Proxy error [%s → %s]: %v", r.URL.Path, target, err)
		http.Error(w, fmt.Sprintf(
			"<html><body style='font-family:sans-serif;padding:40px'>"+
				"<h2>&#128683; Upstream Unavailable</h2>"+
				"<p><b>Route:</b> %s</p>"+
				"<p><b>Target:</b> %s</p>"+
				"<p><b>Error:</b> %s</p>"+
				"<p>Pastikan aplikasi di %s sudah berjalan.</p>"+
				"</body></html>",
			basePath, target, err.Error(), target,
		), http.StatusBadGateway)
	}

	return http.StripPrefix(basePath, proxy)
}

// ── Nginx Config Generation ───────────────────────────────────────────────────

var nginxSnippetTemplate = `# ═══════════════════════════════════════════════════════════════════
# AUTO-GENERATED by HandlerPortProxy — DO NOT EDIT MANUALLY
# Dashboard : http://localhost:{{.AdminPort}}/adminwebui
# Generated : {{.Timestamp}}
# ═══════════════════════════════════════════════════════════════════

# Admin Dashboard
location /adminwebui/ {
    proxy_pass         http://127.0.0.1:{{.AdminPort}}/adminwebui/;
    proxy_set_header   Host $host;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto $scheme;
    proxy_http_version 1.1;
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "upgrade";
}
location /adminwebui { return 301 /adminwebui/; }

# Proxy API (used by admin dashboard)
location /api/ {
    proxy_pass         http://127.0.0.1:{{.AdminPort}}/api/;
    proxy_set_header   Host $host;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_http_version 1.1;
}
{{range .Routes}}{{if .Enabled}}
# {{.Name}}{{if .Description}} — {{.Description}}{{end}}
location {{.Path}}/ {
    proxy_pass         http://127.0.0.1:{{$.AdminPort}}{{.Path}}/;
    proxy_set_header   Host $host;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto $scheme;
    proxy_http_version 1.1;
    proxy_set_header   Upgrade $http_upgrade;
    proxy_set_header   Connection "upgrade";
    proxy_read_timeout 86400s;
    proxy_buffering    off;
}
location {{.Path}} { return 301 {{.Path}}/; }
{{end}}{{end}}`

type SnippetData struct {
	AdminPort int
	Timestamp string
	Routes    []Route
}

func GenerateNginxSnippet() error {
	configMu.RLock()
	data := SnippetData{
		AdminPort: appConfig.AdminPort,
		Timestamp: time.Now().Format("2006-01-02 15:04:05"),
		Routes:    appConfig.Routes,
	}
	snippetPath := appConfig.NginxSnippetPath
	configMu.RUnlock()

	tmpl, err := template.New("nginx").Parse(nginxSnippetTemplate)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}
	if err := os.WriteFile(snippetPath, buf.Bytes(), 0644); err != nil {
		return fmt.Errorf("write snippet: %w", err)
	}
	log.Printf("✓ Nginx snippet → %s", snippetPath)
	return nil
}

func GetNginxSnippet() (string, error) {
	configMu.RLock()
	data := SnippetData{
		AdminPort: appConfig.AdminPort,
		Timestamp: time.Now().Format("2006-01-02 15:04:05"),
		Routes:    appConfig.Routes,
	}
	configMu.RUnlock()
	tmpl, err := template.New("nginx").Parse(nginxSnippetTemplate)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func ReloadNginx() (string, error) {
	for _, args := range [][]string{
		{"sudo", "-n", "nginx", "-s", "reload"},
		{"sudo", "-n", "systemctl", "reload", "nginx"},
		{"sudo", "-n", "s6-svc", "-r", "/run/service/svc-nginx"},
	} {
		out, err := exec.Command(args[0], args[1:]...).CombinedOutput()
		if err == nil {
			return "nginx reloaded successfully ✓\n" + string(out), nil
		}
	}
	return "⚠ Auto-reload gagal (sudo butuh password).\n\nJalankan manual:\n  sudo nginx -s reload", fmt.Errorf("all reload methods failed")
}
